services:
  http_endpoint:
    container_name: http_endpoint
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8060:8050"
    volumes:
      - http_endpoint_data:/var/www/app/data
    environment:
      - APP_ENV=production

volumes:
  http_endpoint_data:
